### ISSUE TITLE
"ka" and "ga" sounds should be converted properly

### ISSUE THREAD

**Issue by sibiarunachalam** [sskjames/tamilscriptconverter#5]
"அன்பு" should be converted as "anbu"

**Comment by sskjames** [comment]
Here are some words with special sounding chars that need to be converted properly.

அகமகிழ்ந்து -> agamagizhnthu
பாடிடுவோம் -> paadiduvoam
ஞானரட்சகர் -> gnaanaratchagar
புகழ் -> pugazh
செங்கோல் -> senggoal
எங்கள் -> enggal
இரக்கம் -> irakkam
மனுடரில் -> manudaril
வருடம் -> varudam
வெகு -> vegu
கிருபை -> kirubai 
குறை -> kurai
தற்காத்து -> tharkaathu

**Comment by sskjames** [comment]
மூர்க்ககுணம் is currently converted as "moorkkakunam". It should be "moorkkagunam".

**Comment by sibiarunachalam** [comment]
Added support to convert only தற்காத்து to tharkaathu properly

**Comment by sskjames** [comment]
"ka" and "ga" sounds are converted properly now almost all the time.
